spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/evoila/cloud-training
          searchPaths: '{application}'
---
spring:
  profiles:
    active: default
server:
  port: 8888